// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdDugGaRHStx6LzQvwNwAHzwDFYFb-Z0E',
    appId: '1:562131548141:web:b1183c1c12714a18e059e4',
    messagingSenderId: '562131548141',
    projectId: 'freelancer-a003b',
    authDomain: 'freelancer-a003b.firebaseapp.com',
    storageBucket: 'freelancer-a003b.firebasestorage.app',
    measurementId: 'G-D0D1RZC5EY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfCNnVb5Dzfc-qsHcleLiqRPRWnNsRbjU',
    appId: '1:562131548141:android:5329347cd9456f8ce059e4',
    messagingSenderId: '562131548141',
    projectId: 'freelancer-a003b',
    storageBucket: 'freelancer-a003b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANz4drQUdJ-jtWRLDZFtNGr7kHSun-VfE',
    appId: '1:562131548141:ios:ae5b686391dc4ca8e059e4',
    messagingSenderId: '562131548141',
    projectId: 'freelancer-a003b',
    storageBucket: 'freelancer-a003b.firebasestorage.app',
    iosBundleId: 'com.example.freelancer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANz4drQUdJ-jtWRLDZFtNGr7kHSun-VfE',
    appId: '1:562131548141:ios:ae5b686391dc4ca8e059e4',
    messagingSenderId: '562131548141',
    projectId: 'freelancer-a003b',
    storageBucket: 'freelancer-a003b.firebasestorage.app',
    iosBundleId: 'com.example.freelancer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdDugGaRHStx6LzQvwNwAHzwDFYFb-Z0E',
    appId: '1:562131548141:web:d195da9ece37915fe059e4',
    messagingSenderId: '562131548141',
    projectId: 'freelancer-a003b',
    authDomain: 'freelancer-a003b.firebaseapp.com',
    storageBucket: 'freelancer-a003b.firebasestorage.app',
    measurementId: 'G-EQKMWYS6GJ',
  );

}